### ISSUE TITLE
세그먼트 컨트롤 커스텀화

### ISSUE THREAD

**Issue by donggeonoh** [DonggeonOh/bithumb-techcamp-ios-1st#14]
코인 리스트의 관심, 원화와 코인 호가, 체결내역, 차트에 사용하는 세그먼트 컨트롤 레이아웃 구성
- [ ] 세그먼트 컨트롤 커스텀화 하기

**Comment by donggeonoh** [comment]
해당 커스텀화 하는 부분은 디자인 관련한 구현사항이여서 기능 위주로 구현하기로 합의하였습니다.
따라서, 해당 구현은 우선순위에서 밀려있어 나중에 구현 할 예정입니다.

**Comment by HJEHA** [comment]
세그먼트 컨트롤를 사용하지 않고
스택 뷰 + 버튼으로 구현함
