### ISSUE TITLE
API 모델(Tiker, Orderbook, Transaction History, Assets status, Candlestick) 구현

### ISSUE THREAD

**Issue by HJEHA** [DonggeonOh/bithumb-techcamp-ios-1st#18]
- [x] Tiker
- [x] Orderbook
- [x] Transaction History
- [x] Assets status
- [x] Candlestick

**Comment by HJEHA** [comment]
Candlestick API는 차트 화면 구현 시 추가한다.

**Comment by donggeonoh** [comment]
코인 차트 화면 구현 하면서 추가 완료
